spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/emdm_d
    username : ${tdaruwalla}
    password : ${password}  # tdaruwalla               #${password}
    driver-class-name: org.postgresql.Driver
 