spring:
  data:
    mongodb:
      uri: mongodb://localhost/test
      repositories:
        enabled: true
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/emdm_d
    username : tdaruwalla
    #password : #${password}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    #database-platform : com.audit.utils.JsonbExtensionToPostgreSQLDialect
    properties:
      hibernate:
        default_schema: emdm

  autoconfigure:
      exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
 
  profiles:
    include: mongo
     
  jackson:
      serialization:
        write-dates-as-timestamps: false
  sleuth:
      sampler:
        percentage: 1  
  application:
    name: Audit-Service      
           
logging:
  level:
    root: fatal
    com.audit: debug
    org.springframework: ERROR
  file: /tmp/config/logs/audit-service.log
server:
    port: 8000
    contextPath: /api
    
swagger:
  api:
    base:
      package: com.audit.controller
    path: /audit.*  
    title: Audit REST API
    description: Spring Boot REST API for Audit
    version: 1.0
    termsofservice:
      url: Terms of service
    contact:
      name: DC
      url:  https://github.com/dwai1714/audit-mongo
      email: dwaip.chowdhury@accionlabs.com
    license:
      name: 
      url: 
